# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_Laplace <- function(rho, lambda, K, Dlogptheta, D2logptheta) {
    .Call(`_EpiLPS_Rcpp_Laplace`, rho, lambda, K, Dlogptheta, D2logptheta)
}

Rcpp_cubicBspline <- function(x, lower, upper, K) {
    .Call(`_EpiLPS_Rcpp_cubicBspline`, x, lower, upper, K)
}

